### ISSUE TITLE
[Question] Why mDNS query responses are dropped?

### ISSUE THREAD

**Issue by mickel8** [rosetta-home/mdns#18]
Hi!
I am trying to use your library to resolve mDNS ICE candidates that different browsers send while establishing the connection.

When ICE candidate ends with `.local` I am trying to resolve it by 
```elixir
Mdns.Client.query("some-string.local")
```
Before it I have done 
```elixir
Mdns.Client.start()
Mdns.Client.register()
```

While executing the above query I can see in wireshark:
![image](https://user-images.githubusercontent.com/24651552/118119424-a367a880-b3ee-11eb-9d0d-2dbe74ed82d9.png)

So there is a queary and a response.

The library logs it by
```
13:20:20.283 [debug] mDNS got response: %DNS.Record{anlist: [%DNS.Resource{bm: [], class: 32769, cnt: 0, data: <<192, 12, 0, 4, 0, 0, 0, 8>>, domain: '3b36c03b-71c2-4fa6-b683-64275f83fc0e.local', func: false, tm: :undefined, ttl: 120, type: 47}], arlist: [%DNS.Resource{bm: [], class: 32769, cnt: 0, data: <<42, 1, 17, 223, 3, 113, 137, 0, 178, 64, 52, 238, 125, 138, 184, 48>>, domain: '3b36c03b-71c2-4fa6-b683-64275f83fc0e.local', func: false, tm: :undefined, ttl: 120, type: :aaaa}], header: %DNS.Header{aa: true, id: 0, opcode: :query, pr: false, qr: true, ra: false, rcode: 0, rd: false, tc: false}, nslist: [], qdlist: []}

13:20:20.283 [debug] mDNS got response: %DNS.Record{anlist: [%DNS.Resource{bm: [], class: 32769, cnt: 0, data: <<192, 12, 0, 4, 0, 0, 0, 8>>, domain: '3b36c03b-71c2-4fa6-b683-64275f83fc0e.local', func: false, tm: :undefined, ttl: 120, type: 47}], arlist: [%DNS.Resource{bm: [], class: 32769, cnt: 0, data: <<42, 1, 17, 223, 3, 113, 137, 0, 178, 64, 52, 238, 125, 138, 184, 48>>, domain: '3b36c03b-71c2-4fa6-b683-64275f83fc0e.local', func: false, tm: :undefined, ttl: 120, type: :aaaa}], header: %DNS.Header{aa: true, id: 0, opcode: :query, pr: false, qr: true, ra: false, rcode: 0, rd: false, tc: false}, nslist: [], qdlist: []}
```
but I don't get any notifications which is probably caused by this code
https://github.com/rosetta-home/mdns/blob/83c687132763f60f58efa9c6fbd2296cd0d24bd7/lib/mdns/client.ex#L115-L127

So my question is why this response is filtered out and I am not notified about it?

Also tried to implement mDNS lookup in C in this way
```c

  char *rest;
  char *candidate_cpy = (char *)calloc(1024, sizeof(char));
  char *prefix = strtok_r(candidate, " ", &rest);
  char *component = strtok_r(NULL, " ", &rest);
  char *proto = strtok_r(NULL, " ", &rest);
  char *prio = strtok_r(NULL, " ", &rest);
  char *addr = strtok_r(NULL, " ", &rest);
  
  char *addr_postfix_ptr = strrchr(addr, '.');
  // check if addr ends with .local
  if (addr_postfix_ptr && !strcmp(addr_postfix_ptr, ".local")) {
    
    struct addrinfo *addrinfo;
    int ret = getaddrinfo(addr, NULL, NULL, &addrinfo);
    fprintf(stderr, "ret %d for %s\n", ret, addr);
    }
 ```
 
 but this piece of code doesn't make any mDNS queries :thinking: It does only DNS ones so I suppose I am missing something about mDNS protocol itself?

**Comment by entone** [comment]
Yeah, the library doesn't handle the `:aaaa` and `47` types that are returned by your services.

It should be relatively easy to add support by adding a few new `handle_device` functions to support the `type` returned in the mDNS answers.

Something like

```
def handle_device(%DNS.Resource{:type => :aaaa, data: data}, device) do
```

and make sure to capture the relevant data you need into the device struct and update the state.

**Comment by entone** [comment]
It looks like type `47` is a NSEC record, and has to do with DNSSEC. I'm not sure how useful that is to you.

The `aaaa` record is the IPv6 response, which is probably what you want to handle.

https://en.wikipedia.org/wiki/List_of_DNS_record_types

**Comment by mickel8** [comment]
Thanks a lot :smiley:

**Comment by entone** [comment]
Feel free to open a PR with support, I'm sure others will find it useful in the future as well.

**Comment by mickel8** [comment]
@entone Could I have one question?
As far as I understand the `Mdns.Client` code, after receiving a response we take our device, iterate over `an` and `ar` lists and for each `%DNS.Resource{}` we update our device fields. 

But I don't know which fields I should update. E.g. for `:type => :ptr` you updates `services` field, for `:type => :srv` we have `:port` update. I suppose that I should also update `services` field for `NSEC` records but how can I know that? Why we e.g. don't update `services` field for `:a` records?

**Comment by entone** [comment]
I'm not totally sure to be honest. The port capture was just recently
added. Someone needed the access to that data.

It would probably make sense at this point to capture just the data you
need to fulfill your requirements. If additional data is needed by people
in the future, they can add it.

As far as I can tell, the data returned is simply the IP address.
